# snippets is used to load a full NGFW configuration
# LINK TO META FILE DOCS

# unique snippet name
name: skeleton_yaml_file
# label used for menu selection
label: Text used for the panhandler menu option
description: Simple description to describe this skillet

# type of device configuration
# common types are panorama, panos, and template
# https://github.com/PaloAltoNetworks/panhandler/blob/develop/docs/metadata_configuration.rst
type: panos
# preload static or default-based templates
extends:

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection: sample

# variables used in the configuration templates
# type_hint defines the form field used by panhandler
# type_hints can be text, ip_address, or dropdown
variables:
  - name: hostname
    description: Firewall hostname
    default: myFirewall
    type_hint: text
  - name: choices
    description: sample dropdown list
    default: choices
    type_hint: dropdown
    dd_list:
      - key: option1
        value: option1
      - key: option2
        value: option2

# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
snippets:
  - name: quick_name
    xpath: /config/devices/restofthe/xmltree
    file: filename.xml
